In [9]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np


In [11]:
my_list=[1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [12]:
arr=np.array(my_list)
arr

array([1, 2, 3, 4, 5, 6])

In [14]:
arr[3]

4

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(arr)


[1 2 3 4 5 6]


In [8]:
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
arr.shape


(6,)

In [15]:
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]
arr=np.array([my_list1,my_list2,my_list3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
arr.shape

(3, 5)

In [17]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
arr[0:2,0:2]


array([[1, 2],
       [6, 7]])

In [19]:
arr[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [34]:
arr[1:3,2:5]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [22]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [15]:
arr.reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [36]:
arr=np.arange( 0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr=np.arange(0,10,step=2)
arr


array([0, 2, 4, 6, 8])

In [39]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [42]:
arr=np.arange(0,10)
arr

arr[3:]=100
arr




array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [43]:
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]
arr=np.array([my_list1,my_list2,my_list3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [47]:
arr[1:,3:]=200
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8, 200, 200],
       [ 11,  12,  13, 200, 200]])

In [48]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr1=arr
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr1[3:]=300
arr

array([  0,   1,   2, 300, 300, 300, 300, 300, 300, 300])

In [55]:
arr1=arr.copy()
arr1

array([  0,   1,   2, 300, 300, 300, 300, 300, 300, 300])

In [57]:
arr1[3:]=700

In [58]:
arr1


array([  0,   1,   2, 700, 700, 700, 700, 700, 700, 700])

In [59]:
arr

array([  0,   1,   2, 300, 300, 300, 300, 300, 300, 300])

In [60]:
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [63]:
 
arr[arr<10]


array([0, 1, 2])

In [64]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
arr1=np.arange(0,10).reshape(5,2)
arr2=np.arange(0,10).reshape(5,2)
arr1*arr2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [68]:
np.ones(4,dtype=int)


array([1, 1, 1, 1])

In [69]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [70]:
np.random.rand(3,3)

array([[0.21938054, 0.6582526 , 0.15903605],
       [0.32346982, 0.08019227, 0.17275843],
       [0.27984205, 0.45552752, 0.05416065]])

In [75]:
np.random.randint(0,100,8).reshape(2,4)

array([[48, 97,  0, 49],
       [19, 75, 32, 25]])

In [76]:
np.random.random_sample((1,5))

array([[0.56510697, 0.17472555, 0.23526886, 0.75170509, 0.25892227]])